/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pvd.view.lists;

import pvd.controller.AddressController;
import pvd.controller.CustomerController;
import pvd.model.Address;
import pvd.model.Customer;
import pvd.view.forms.CustomerForm;

/**
 *
 * @author denis
 */
public class CustomerList extends List {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomerList.class.getName());

    /**
     * Creates new form CostumerList
     */
    public CustomerList() {
        super();
        initComponents();
    }

    @Override
    public boolean delete(int id) {
        CustomerController controller = new CustomerController();
        boolean deleted = controller.delete(id);
        return deleted;
    }

    @Override
    protected void openCreateForm() {
        new CustomerForm(this).setVisible(true);
    }

    @Override
    protected void openUpdateForm(int itemToUpdateId) {
        new CustomerForm(this, itemToUpdateId).setVisible(true);
    }

    @Override
    protected String[] getColumns() {
        return new String[]{
            "ID",
            "Nome",
            "Código",
            "Telefone",
            "Email",
            "Estado",
            "Cidade",
            "Cep",
            "Rua",
            "Número",
            "Complemento",
        };
    }


@Override
protected String[][] getRows() {
    CustomerController customerController = new CustomerController();
    AddressController addressController = new AddressController();
    
    java.util.List<Customer> customers = customerController.getAll();

    String[][] rows = new String[customers.size()][getColumns().length];

    for (int i = 0; i < customers.size(); i++) {
        Customer customer = customers.get(i);
        Address address = addressController.getById(customer.getAddressId());

        rows[i][0] = String.valueOf(customer.getId());
        rows[i][1] = customer.getName();
        rows[i][2] = (customer.getCode() != null) ? customer.getCode() : "-";
        rows[i][3] = (customer.getPhoneNumber() != null) ? customer.getPhoneNumber() : "-";
        rows[i][4] = (customer.getEmail() != null) ? customer.getEmail() : "-";
        
        if (address != null) {
            rows[i][5] = (address.getState() != null) ? address.getState() : "-";
            rows[i][6] = (address.getCity() != null) ? address.getCity() : "-";
            rows[i][7] = (address.getZipCode() != null) ? address.getZipCode() : "-";
            rows[i][8] = (address.getStreet() != null) ? address.getStreet() : "-";
            rows[i][9] = String.valueOf(address.getNumber());
            rows[i][10] = (address.getComplement() != null) ? address.getComplement() : "-";
        } else {
            for (int j = 5; j < getColumns().length; j++) {
                rows[i][j] = "-";
            }
        }
    }

    return rows;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 755, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CustomerList().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
