/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pvd.view.lists;

import javax.swing.table.DefaultTableModel;
import pvd.view.forms.ProductForm;
import pvd.view.helpers.WindowHelper;

/**
 *
 * @author denis
 */
public abstract class List extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(List.class.getName());

    /**
     * Creates new form List
     */
    public List() {
        initComponents();
        this.listData();
        WindowHelper.centralize(this);
    }

    protected abstract String[][] getRows();

    protected abstract String[] getColumns();

    public void refreshTable() {
        this.listData();
    }

    protected void listData() {
        String[][] rows = getRows();
        String[] columns = getColumns();

        DefaultTableModel model = new DefaultTableModel(rows, columns);
        table.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        createButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table);

        createButton.setText("Criar");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        editButton.setText("Editar");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Deletar");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createButton)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createButton)
                    .addComponent(editButton)
                    .addComponent(deleteButton))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected abstract void openCreateForm();

    protected abstract void openUpdateForm(int itemToUpdateId);

    protected abstract boolean delete(int id);

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        this.openCreateForm();
    }//GEN-LAST:event_createButtonActionPerformed

    private int getSelectedItemId() {
        int selectedRow = table.getSelectedRow();
        Object idValue = table.getValueAt(selectedRow, 0);
        if (idValue == null) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "O item selecionado não possui ID válido.",
                    "Erro",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
            return 0;
        }

        int id = Integer.parseInt(idValue.toString());
        return id;
    }

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int id = this.getSelectedItemId();

        if (id == 0) {
            return;
        }

        if (id < 1) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Por favor, selecione um item para excluir.",
                    "Nenhuma seleção",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int confirm = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Tem certeza que deseja excluir o item com ID " + id + "?",
                "Confirmar exclusão",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            try {
                boolean deleted = this.delete(id);

                if (deleted) {
                    javax.swing.JOptionPane.showMessageDialog(
                            this,
                            "Item excluído com sucesso.",
                            "Sucesso",
                            javax.swing.JOptionPane.INFORMATION_MESSAGE
                    );
                    this.refreshTable();
                } else {
                    javax.swing.JOptionPane.showMessageDialog(
                            this,
                            "Falha ao excluir o item.",
                            "Erro",
                            javax.swing.JOptionPane.ERROR_MESSAGE
                    );
                }
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Erro ao excluir: " + e.getMessage(),
                        "Erro",
                        javax.swing.JOptionPane.ERROR_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        int id = this.getSelectedItemId();

        if (id == 0) {
            return;
        }

        if (id < 1) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Por favor, selecione um item para editar.",
                    "Nenhuma seleção",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        
        this.openUpdateForm(id);
    }//GEN-LAST:event_editButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
