/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pvd.view.lists;

import pvd.controller.ProductController;
import pvd.model.Product;
import pvd.view.forms.ProductForm;

/**
 *
 * @author denis
 */
public class ProductList extends List {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProductList.class.getName());

    /**
     * Creates new form ProductList
     */
    public ProductList() {
        super();
        initComponents();
    }

    public void refreshTable() {
        this.listData();
    }

    @Override
    public boolean delete(int id) {
        ProductController productController = new ProductController();
        boolean deleted = productController.delete(id);
        return deleted;
    }
    
    @Override
    protected void openCreateForm() {
        new ProductForm(this).setVisible(true);
    }
    
    @Override
    protected void openUpdateForm(int itemToUpdateId) {
        new ProductForm(this, itemToUpdateId).setVisible(true);
    }

    @Override
    protected String[] getColumns() {
        return new String[]{
            "ID",
            "Nome",
            "Unidade",
            "Preço",
            "Quantidade em estoque",
            "Data da última venda"
        };
    }

    @Override
    protected String[][] getRows() {
        ProductController controller = new ProductController();
        java.util.List<Product> products = controller.getAll();

        String[][] rows = new String[products.size()][getColumns().length];

        for (int i = 0; i < products.size(); i++) {
            Product product = products.get(i);

            rows[i][0] = String.valueOf(product.getId());
            rows[i][1] = product.getName();
            rows[i][2] = product.getUnit();
            rows[i][3] = String.format("%.2f", product.getPrice());
            rows[i][4] = String.format("%.2f", product.getStockQuantity());
            rows[i][5] = (product.getLastSaleDate() != null)
                    ? new java.text.SimpleDateFormat("yyyy-MM-dd").format(product.getLastSaleDate())
                    : "-";
        }

        return rows;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de produtos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 753, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProductList().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
