/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cadastro_de_clientes.view;

import cadastro_de_clientes.Database;
import cadastro_de_clientes.model.Costumer;
import cadastro_de_clientes.view.forms.JFrRegistryCostumer;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;

/**
 *
 * @author denis
 */
public class JFrListCostumers extends JFrList {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrListCostumers.class.getName());

    private ArrayList<Costumer> costumers = new ArrayList<>();

    /**
     * Creates new form JFrListCostumers
     */
    public JFrListCostumers() {
        super();
        costumers = new ArrayList<>();
        this.listData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 815, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void openForm() {
        JFrRegistryCostumer form = new JFrRegistryCostumer();
        form.setVisible(true);
    }

    @Override
    protected String[][] getRows() {
        fetchCostumers();
        String[][] rows = new String[costumers.size()][12];

        for (int i = 0; i < costumers.size(); i++) {
            Costumer c = costumers.get(i);
            rows[i][0] = String.valueOf(c.getId());
            rows[i][1] = c.getName();
            rows[i][2] = c.getPhone();
            rows[i][3] = c.getEmail();
            rows[i][4] = c.getCep();
            rows[i][5] = c.getStreet();
            rows[i][6] = c.getNumber();
            rows[i][7] = c.getComplement();
            rows[i][8] = c.getNeighborhood();
            rows[i][9] = c.getCity();
            rows[i][10] = c.getState();
            rows[i][11] = c.getCpf();
        }
        return rows;
    }

    @Override
    protected String[] getColumns() {
        return new String[]{
            "Id", "Nome", "Telefone", "Email", "CEP", "Rua", "Número", "Complemento",
            "Bairro", "Cidade", "Estado", "CPF"
        };
    }

    private void fetchCostumers() {
        costumers.clear();
        String sql = "SELECT * FROM costumer";

        try (Connection conn = Database.getConnection(); Statement stmt = conn.createStatement(); ResultSet rs = stmt.executeQuery(sql)) {

            while (rs.next()) {
                costumers.add(new Costumer(
                        rs.getInt("id"),
                        rs.getString("name"),
                        rs.getString("phone"),
                        rs.getString("email"),
                        rs.getString("cep"),
                        rs.getString("street"),
                        rs.getString("number"),
                        rs.getString("complement"),
                        rs.getString("neighborhood"),
                        rs.getString("city"),
                        rs.getString("state"),
                        rs.getString("cpf")
                ));
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    @Override
    protected void deleteItem(int selectedRow) {
        String sql = "DELETE FROM costumer WHERE id = ?";
        Costumer c = getSelectedCostumer(selectedRow);
        try (java.sql.Connection conn = Database.getConnection(); java.sql.PreparedStatement stmt = conn.prepareStatement(sql)) {

            stmt.setInt(1, c.getId());
            int rowsAffected = stmt.executeUpdate();

            if (rowsAffected > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Cliente excluído com sucesso!");
                costumers.remove(selectedRow);
                listData();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Falha ao excluir cliente.");
            }

        } catch (java.sql.SQLException ex) {
            ex.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
        }
    }

    @Override
    protected void editItem(int selectedRow) {

        Costumer c = getSelectedCostumer(selectedRow);

        JFrRegistryCostumer form = new JFrRegistryCostumer();

        form.getNameText().setText(c.getName());
        form.getPhoneNumberText().setText(c.getPhone());
        form.getEmailText().setText(c.getEmail());
        form.getCpfText().setText(c.getCpf());
        form.getCepText().setText(c.getCep());
        form.getStreetText().setText(c.getStreet());
        form.getNumberText().setText(c.getNumber());
        form.getComplementText().setText(c.getComplement());
        form.getNeighborhoodText().setText(c.getNeighborhood());
        form.getCityText().setText(c.getCity());
        form.getStateComboBox().setSelectedItem(c.getState());

        for (ActionListener al : form.getSaveButton().getActionListeners()) {
            form.getSaveButton().removeActionListener(al);
        }

        form.getSaveButton().addActionListener(evt -> {
            c.setName(form.getNameText().getText());
            c.setPhone(form.getPhoneNumberText().getText());
            c.setEmail(form.getEmailText().getText());
            c.setCpf(form.getCpfText().getText());
            c.setCep(form.getCepText().getText());
            c.setStreet(form.getStreetText().getText());
            c.setNumber(form.getNumberText().getText());
            c.setComplement(form.getComplementText().getText());
            c.setNeighborhood(form.getNeighborhoodText().getText());
            c.setCity(form.getCityText().getText());
            c.setState((String) form.getStateComboBox().getSelectedItem());

            String sql = "UPDATE costumer SET name=?, phone=?, email=?, cpf=?, cep=?, street=?, number=?, complement=?, neighborhood=?, city=?, state=? WHERE id=?";
            try (java.sql.Connection conn = Database.getConnection(); java.sql.PreparedStatement stmt = conn.prepareStatement(sql)) {

                stmt.setString(1, c.getName());
                stmt.setString(2, c.getPhone());
                stmt.setString(3, c.getEmail());
                stmt.setString(4, c.getCpf());
                stmt.setString(5, c.getCep());
                stmt.setString(6, c.getStreet());
                stmt.setString(7, c.getNumber());
                stmt.setString(8, c.getComplement());
                stmt.setString(9, c.getNeighborhood());
                stmt.setString(10, c.getCity());
                stmt.setString(11, c.getState());
                stmt.setInt(12, c.getId());

                stmt.executeUpdate();

                javax.swing.JOptionPane.showMessageDialog(form, "Cliente atualizado com sucesso!");
                listData();
                form.dispose();

            } catch (java.sql.SQLException ex) {
                ex.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(form, "Erro: " + ex.getMessage());
            }
        });

        form.setVisible(true);
    }

    public Costumer getSelectedCostumer(int rowIndex) {
        if (rowIndex >= 0 && rowIndex < costumers.size()) {
            return costumers.get(rowIndex);
        }
        return null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrListCostumers().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
