/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cadastro_de_clientes.view;

import cadastro_de_clientes.view.helper.Helper;

/**
 *
 * @author denis
 */
public class JFrMainWindow extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrMainWindow.class.getName());

    /**
     * Creates new form JFrMainWindow
     */
    public JFrMainWindow() {
        initComponents();
        Helper.centralize(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mainMenu = new javax.swing.JMenu();
        registryMenu = new javax.swing.JMenu();
        costumerRegistryMenuItem = new javax.swing.JMenuItem();
        supplierRegistryMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainMenu.setText("Tela Inicial");
        jMenuBar1.add(mainMenu);

        registryMenu.setText("Cadastros");

        costumerRegistryMenuItem.setText("Clientes");
        costumerRegistryMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listCostumers(evt);
            }
        });
        registryMenu.add(costumerRegistryMenuItem);

        supplierRegistryMenuItem.setText("Fornecedores");
        supplierRegistryMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listSuppliers(evt);
            }
        });
        registryMenu.add(supplierRegistryMenuItem);

        jMenuBar1.add(registryMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 699, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listCostumers(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listCostumers
        new JFrListCostumers().setVisible(true);
    }//GEN-LAST:event_listCostumers

    private void listSuppliers(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listSuppliers
        new JFrListSuppliers().setVisible(true); 
        System.out.println("TESTE");
    }//GEN-LAST:event_listSuppliers

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrMainWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem costumerRegistryMenuItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mainMenu;
    private javax.swing.JMenu registryMenu;
    private javax.swing.JMenuItem supplierRegistryMenuItem;
    // End of variables declaration//GEN-END:variables
}
